Patient_State/main/default/objects/Patient_State__c/Patient_State__c.object-meta.xml
<CustomObject>
    <label>Patient State</label>
    <nameField>
        <displayFormat>PS-{0000}</displayFormat>
        <label>Patient State Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Patient State</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Patient_State/main/default/objects/Patient_State__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Patient State</relationshipLabel>
    <relationshipName>Patient_State</relationshipName>
    <type>Lookup</type>
</CustomField>

Patient_State/main/default/objects/Patient_State__c/fields/Current_State__c.field-meta.xml
<CustomField>
    <fullName>Current_State__c</fullName>
    <label>Current State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Readjust</fullName>
            </value>
            <value>
                <fullName>Escalated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Patient_State/main/default/objects/Patient_State__c/fields/Display_Status__c.field-meta.xml
<CustomField>
    <fullName>Display_Status__c</fullName>
    <label>Display Status</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

Patient_State/main/default/objects/Patient_State__c/fields/Orientation__c.field-meta.xml
<CustomField>
    <fullName>Orientation__c</fullName>
    <label>Orientation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Sitting</fullName>
            </value>
            <value>
                <fullName>Laying</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Patient_State/main/default/objects/Patient_State__c/fields/Time_in_Position__c.field-meta.xml
<CustomField>
    <fullName>Time_in_Position__c</fullName>
    <label>Time in Position</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Patient_State/main/default/classes/PressureSensorController.cls
public class PressureSensorController
{
    @AuraEnabled(cacheable=false)
    public static Patient_State__c getPatientState(String accountId)
    {
        List<Patient_State__c> states = [SELECT Id,Name,Account__c,Current_State__c,Display_Status__c,Orientation__c,
                                         PatientId__c,Time_in_Position__c
                                         FROM Patient_State__c
                                         WHERE Account__c= :accountId
                                         ORDER BY LastModifiedDate DESC
                                         LIMIT 1];
        
        Patient_State__c ps;
        if (states.isEmpty()) {
            //create a place holder to leverage
            ps = new Patient_State__c();
            ps.Account__c = accountId;
            insert ps;
        } else {
            ps = states[0];
        }
        return ps;
    }
    
    @AuraEnabled(cacheable=false)
    public static String getCardTitle()
    {
        String result = 'Pressure Sensor State';
        List<HealthCloudGA__CardView_Dropdown__c> vals = HealthCloudGA__CardView_Dropdown__c.getAll().values();
        for (HealthCloudGA__CardView_Dropdown__c val : vals)
        {
            if (val.HealthCloudGA__Sub_Category__c == 'Pressure Sensor')
            {
            	result = val.Name;
            }
        }
        return result;
    }
}