Patient_State/main/default/objects/Image_List__mdt/Image_List__mdt.object-meta.xml
<CustomObject>
    <label>Image List</label>
    <pluralLabel>Images List</pluralLabel>
</CustomObject>

Patient_State/main/default/objects/Image_List__mdt/fields/Image_Config__c.field-meta.xml
<CustomField>
    <fullName>Image_Config__c</fullName>
    <label>Image Config</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

Patient_State/main/default/classes/DynamicImageDisplayController.cls
public class DynamicImageDisplayController {

    @AuraEnabled
    public static String getConfig(String configName)
    {
        List<Image_List__mdt> recs = [SELECT Id, DeveloperName, Image_Config__c
                                      FROM Image_List__mdt
                                     WHERE DeveloperName = :configName];
        
        String retVal = '';
        for (Image_List__mdt rec : recs)
        {
            retVal = rec.Image_Config__c;
        }
        return retVal;
    }
}